services:
  # redis:
  #   container_name: redis
  #   image: 'redis:7.0.8-alpine'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - ./tmp/redis:/bitnami/redis/data

  # web:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #   command: bundle exec rails s -b 0.0.0.0

  postgres:
    container_name: postgres
    image: 'postgres:15.2-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - DB_SOURCE=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${SSL_MODE}
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

