# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 'ci-test'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-2
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DATABASE: simple_bank
          POSTGRES_PORT: 5432
          SSL_MODE: disable
        # set healtchecks
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
    - name: Check out codeinto the Go module directory
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test

